### ISSUE TITLE
deploy.sh not providing output

### ISSUE THREAD

**Issue by SimonJohnG** [ukncsc/lme#80] opened 2020-10-06 15:54 UTC
On running deploy.sh no passwords were provided and no windows zip file was generated. Please help.

**Comment by a-d-a-m-b** [comment] 2020-10-07 07:57
Hello @SimonJohnG 

Did the deploy.sh script complete? Do you have a copy of the output?

**Comment by SimonJohnG** [comment] 2020-10-07 09:34
Hi Adam,

It did complete but when capturing the output I noticed the error ‘LME requires 8gb’ so upped the virtual machine and ran the script again. This time the script has run further and currently sitting on ‘Waiting for elaticsearch to be ready’, this has been the case for around one hour, is this expected?

Kind regards
Simon

**Comment by a-d-a-m-b** [comment] 2020-10-07 12:22
This symptom can be indicative of a few issues. 

https://github.com/ukncsc/lme/issues/73
https://github.com/ukncsc/lme/issues/40

are both examples.

But to find out why, what does the output of `docker service logs lme_elasticsearch --tail 20 --timestamps` look like if you were able to run in a different terminal?

**Comment by SimonJohnG** [comment] 2020-10-07 12:49
Hi Adam,

Please find attached current progress, this was from the second run of the script due to incorrect memory requirement.

Kind regards
Simon

**Comment by a-d-a-m-b** [comment] 2020-10-07 12:57
can you provide the output from `docker service logs lme_elasticsearch --tail 20 --timestamps`?

**Comment by SimonJohnG** [comment] 2020-10-07 13:18
I have little Ubuntu skills, is this what you’re looking for?

**Comment by a-d-a-m-b** [comment] 2020-10-07 13:27
It looks like not enough memory is being made available to the Docker daemon, and thus Elasticsearch.

` "Caused by: javax.crypto.BadPaddingException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)",`

What is the size of the memory on the machine? and what is the content of line 29 in the `/opt/lme/Chapter 3 Files/docker-compose-stack-live.yml` (it should look like `"ES_JAVA_OPTS=-Xms##g -Xmx##g"`

**Comment by SimonJohnG** [comment] 2020-10-07 13:39
Currently its 10Gb

The content is: "ES_JAVA_OPTS=-Xmsram-countg -Xmxram-countg"

**Comment by a-d-a-m-b** [comment] 2020-10-07 14:31
Can you increase the RAM (assuming it is a virtual machine)? The error indicates that elasticsearch needs more memory (tag size : 16GB) than it has available (buffer remaining : 2GB)

The memory requirement is stated in the pre-requisites also: `A Linux server with 2 processor cores and at least 16GB RAM. We will install our database (Elasticsearch) and dashboard software on this machine. This is all taken care of through Docker containers. `

https://github.com/ukncsc/lme/blob/master/docs/prerequisites.md

**Comment by SimonJohnG** [comment] 2020-10-08 06:57
Still ‘waiting for elasticsearch to be ready 16 hours after increasing to 16gb, should I rebuild with the correct memory requirement and start again rather than just running the script again?

**Comment by SimonJohnG** [comment] 2020-10-08 09:07
After completing a clean install all is good.

My next problems is under section 3.3.2 Install Winlogbeat

Does Winlogbeat need to be installed or just the actions listed below it?

From: Simon Gilkes
Sent: 08 October 2020 07:57
To: 'ukncsc/lme' <reply@reply.github.com>; ukncsc/lme <lme@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [ukncsc/lme] deploy.sh not providing output (#80)

Still ‘waiting for elasticsearch to be ready 16 hours after increasing to 16gb, should I rebuild with the correct memory requirement and start again rather than just running the script again?

**Comment by SimonJohnG** [comment] 2020-10-08 09:54
As section 3.3.2 install Winlogbeat instruction is pretty atrocious can you help with the following:


·         On the windows event collector server unzip the winlogbeat file and replace 'winlogbeat.yml' with the one that came in 'files_for_windows.zip' **that’s ok**


·         If your certificates are not in the same place as the locations in the file please change this too. **I assume in the same folder as 'winlogbeat.yml'**


·         Pay attention to the double slashes, these are required! **There are no double slashes so don’t understand this comment**


·         Copy winlogbeat-sysmon.js and winlogbeat-security.js file from the latest winlogbeat download and place them in the directories listed below
C:\\Program Files\\lme\\winlogbeat-7.6.1-windows-x86_64\\module\\sysmon\\config\\winlogbeat-sysmon.js
C:\\Program Files\\lme\\winlogbeat-7.6.1-windows-x86_64\\module\\security\\config\\winlogbeat-security.js

**In Windows you can’t use \ let alone \\ in windows directories **

I’m obvious not catching on here???






From: Simon Gilkes
Sent: 08 October 2020 10:07
To: 'ukncsc/lme' <reply@reply.github.com>; 'ukncsc/lme' <lme@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [ukncsc/lme] deploy.sh not providing output (#80)

After completing a clean install all is good.

My next problems is under section 3.3.2 Install Winlogbeat

Does Winlogbeat need to be installed or just the actions listed below it?

From: Simon Gilkes
Sent: 08 October 2020 07:57
To: 'ukncsc/lme' <reply@reply.github.com<mailto:reply@reply.github.com>>; ukncsc/lme <lme@noreply.github.com<mailto:lme@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [ukncsc/lme] deploy.sh not providing output (#80)

Still ‘waiting for elasticsearch to be ready 16 hours after increasing to 16gb, should I rebuild with the correct memory requirement and start again rather than just running the script again?

**Comment by duncan-ncc** [comment] 2020-10-08 11:32
Hello Simon,

"If your certificates are not in the same place as the locations in the file please change this too."

If you open winlogbeat.yml which is inside the files_for_windows.zip you will see a number of variables set such as "ssl.certificate" and "ssl.key".
These variables do contain double slashes, As it is a YML fie you can use \ & \\ as path markers, This is done to avoid YAML parser errors.

**Comment by SimonJohnG** [comment] 2020-10-08 12:11
Hi Adam,

Not clear in instruction that its referring to editing winlogbeat.yml, I moved the files to the correct location via error messages. Managed to log into server but not convinced it’s working, also imported dashboards dashboard 0.1.1b, 0.1.2 failed and v0.2.0, 0.3.0 haven’t got a clue what to do with these.

Maybe its fatigue after spending 3 days with zero result.

Thanks for your assistance

**Comment by duncan-ncc** [comment] 2020-10-08 12:30
Hello Simon,

I will make a note on the roadmap of providing more clarity around some of the more hands on steps.

You probably do not want the old versions of the dashboards but instead just the latest (the one with the largest number). 

If you follow the checklist at the bottom of Chapter 3 then you should see logs inside kibana.

Regards,
Duncan

**Comment by SimonJohnG** [comment] 2020-10-08 12:45
Hi Duncan,

Thank you.

I have downloaded dashboards but I can’t find any reference contained within them to change to point to my server, even more worrying I can’t see that instruction in the instructions and longer!!

In interface shown on the website instructions is different to mine so finding it difficult to locate items that now appear in completely different areas.

Kind regards
Simon

**Comment by a-d-a-m-b** [comment] 2020-10-08 12:50
https://github.com/ukncsc/lme/blob/master/docs/chapter4.md

Section 4.1.1 states how to amend the dashboard's ndjson file to point to your server (which is what I assume you're referring to)

**Comment by a-d-a-m-b** [comment] 2020-10-08 12:52
Hi Simon. I think it is best if we close this issue as we have resolved the original problem around the memory requirements for Elasticsearch. We have since strayed into another issue that Duncan has resolved (the Yaml issue), and it looks like we're starting a new one.

As Duncan has already commented, we have made a note of the documentation changes you suggested. We are looking into ways the documentation could be improved but we will accept suggested changes via a pull request.

If you have any further issues, please feel free to open a new github issue, as this allows others to easily find similar issues and resolution steps in the future.

**Closed as completed by a-d-a-m-b** 2020-10-08 12:52 UTC
