### ISSUE TITLE
Kibana Dashboards with Winlogbeat v7  [BUG]

### ISSUE THREAD

**Issue by nickjossy** [ukncsc/lme#6] opened 2019-04-27 16:45 UTC
In the latest version of Winlogbeat (v7) they have renamed a large number of fields as detailed here; https://www.elastic.co/guide/en/beats/libbeat/current/breaking-changes-7.0.html.  

If you import the Kibana dashboard then none of the visualisations retrieve any results because of this.   As these new field names do not exist in the Index Pattern you can't correct the visualisations without first refreshing the field list of the Index Pattern.  This in turn breaks a lot of other visualisations as the fields do not yet exist.

It would be a good idea to specific which versions of products the documentation, config files and templates have been tested on.  I also found that the deploy script in Chapter 3 does not work on Ubuntu 19.04, but works mine on 18.04

**Comment by duncan-ncc** [comment] 2019-04-27 17:59
Hi, Thanks for the feedback, As the Winlogbeat changes are breaking changes we will look into this and see what the best way forward is.

In regards to the deployment script can you please provide more information on what portion did not work.
The script was written to support 18.04 as it is the current LTS however this is probably something that should be highlighted in the documentation.

**Comment by nickjossy** [comment] 2019-04-29 17:28
Hi, It was the Docker install commands that failed.  The error was something like "Package 'docker-ce' has no installation candidate".  There were a number of articles on the internet pointing at this error when 18.04 first came out as the package was not available.  So I suspect it may just be a timing issue with 19.04 being relatively new.

**Comment by duncan-ncc** [comment] 2019-04-29 22:52
@nickjossy We use the Docker convenience script to handle the Docker install in an attempt to let LME work on as many platforms as Docker supports, it does look like 19.04 is not on the [Docker supported list](https://docs.docker.com/install/linux/docker-ce/ubuntu/).

**Comment by nebblkshts** [comment] 2019-04-30 19:17
So does this mean I am not crazy? I got everything done and pulled up the dashboard and see nothing.

**Comment by duncan-ncc** [comment] 2019-04-30 21:09
@nebblkshts Yes, If you used Winlogbeat v7 the dashboard will not display as intended. I suspect that the easiest fix for this is going to be releasing a set of dashboards with compatibility for WLBv7

**Comment by nickjossy** [comment] 2019-04-30 21:56
In the Winlogbeat zip file there's also an uninstall powershell script.  Run that and then just download Winlogbeat v6.7.1 and go back to step 3.3.2.  This worked fine for me:

https://www.elastic.co/downloads/past-releases/winlogbeat-6-7-1

**Comment by nebblkshts** [comment] 2019-05-01 00:06
Thank you sir

**Comment by nebblkshts** [comment] 2019-05-01 19:44
I backed out of 7 renamed the program data folder. Rebooted then configured the yml file did the install and I have the same issue I must have missed something.

**Comment by duncan-ncc** [comment] 2019-05-01 21:11
@nickjossy We are going to change the documentation to highlight the supported linux versions and which version of WLB we support. It is most likely that we will support Winlogbeat version 7 onwards and no longer provide new dashboards for Winlogbeat version 6.

I will update this issue with the commit link after these changes are made.

**Comment by shane-m1** [comment] 2019-05-02 09:29
@nickjossy thanks for bringing this to our attention. Poor timing with Winlogbeat version changes, but at least we’ve learnt something new and will add this symptom to the troubleshooting in case of it happening again. Although, we’re going to be clearer about version number of all the components.
Duncan’s making a set of version 7 WLB dashboards today, stay tuned!

@nebblkshts are you still having issues?

**Closed as completed** 2019-05-02 12:21 UTC
Labels: bug

**Comment by nebblkshts** [comment] 2019-05-02 13:55
Yes, I still have a problem. I think it is something I missed. Trying to backtrack through to see what I missed since downgrading did not help.

**Comment by nickjossy** [comment] 2019-05-02 16:54
@nebblkshts are you seeing any log data when you click on the Discover tab in Kibana?

**Comment by nebblkshts** [comment] 2019-05-02 20:04
None.

**Comment by duncan-ncc** [comment] 2019-05-03 10:02
@nebblkshts Have you checked over the checklists at the end of each chapter to see at which point the logs are getting to if they are not appearing in kibana, I'd recommend checking the box where the windows logs are sent to (in event viewer > forwarded logs)

**Comment by nebblkshts** [comment] 2019-05-03 12:59
@duncan-ncc Ok, so I blew away my Ubuntu 18.04 and started all over. I got the same result as last time where it looks like it adds some of these docker containers 2 or 3 times. The last time I had one of our Dev team who knew more than I did about Docker and he cleaned up but I still had issues. So I wanted to stop here this time and make sure this is the result I should see. I have 12 containers and those in running state are:

- lme_nginx.1
- lme_curator.1
- lme_logstash.1
- lme_kibana.1
- lme_elasticsearch.1

Shutdown and errored with "task: non-zero exit (1)":
- \_ lme_nginx.1
- \_ lme_nginx.1
- lme_nginx.1
- \_ lme_nginx.1
- lme_curator.1
-  \_ lme_curator.1
- lme_curator.1

**Comment by duncan-ncc** [comment] 2019-05-03 13:12
@nebblkshts The top containers look correct. The shutdown and errored look like old containers from previous? 

You can use ```docker container prune``` to remove these old shutdown containers.

**Comment by nebblkshts** [comment] 2019-05-03 15:28
The issue is there should not be any previous. This was a clean install on a new drive. I ran your command but the system keeps regenerating the containers. 

I proceeded and tried both version 7 and 6.71 with the same results I had before the clean install. No data. I see the forwarded logs coming in from other windows machines. I had all the checklist items prior to Chapter 3.
