### ISSUE TITLE
[BUG]Data stopped @ Jul 24, 2021 - 16:59:59.987

### ISSUE THREAD

**Issue by dirka1** [ukncsc/lme#111] opened 2021-07-27 22:19 UTC
**Describe the issue**
LME - testing for 4 months, no issues. As of July 24th data no longer displays. (Nothing was completed on the Windows event collector/Linux server)

**To Reproduce**
No data displays past July 24th @ 16:59:59

**Expected behavior**
Data current up to last 15 minutes.

**Screenshots**

**Windows Event Collector (please complete the following information):**
 - OS: Windows Server 2019
 - WEC Config - how do I check this?
 - Winlogbeat Config - how do I check this?
 - Winlogbeat.exe version WinlogBeat 7.9.2
 - sysmon config how do I check this?
 - sysmon executable 11.11

**Linux Server (please complete the following information):**
 - Docker: 20.10.5
 - Docker compose stack file version: how do I check this?
 - Linux:  Ubuntu 20.04.2 LTS
 -  Logstash Version - Version 0.3 - 06/07/2020

**Additional context**
I apologize in advance - not sure if this is a bug or something on my end, not sure what to look for in terms of troubleshooting steps and am willing to delete the VM and start anew - just want to avoid if possible, have 4 months of data available.

HD/RAM/Proc specs are good, not low on that. Just not sure what caused this to stop reporting. Windows Event log data check came back good as well.

**Comment by dirka1** [comment] 2021-07-27 22:38
Ran this command - sudo docker service logs lme_logstash --tail 20 --timestamps

Results - 
`2021-07-27T22:36:47.443692659Z lme_logstash.1.esig3bbpn4e9@s-elk    | [2021-07-27T22:36:47,443][WARN ][logstash.outputs.elasticsearch][main][d3ff967aa3881b4eba7f916b7d5bf063a925b5a3df8207d4501bb4bfa2808d6b] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"winlogbeat-27.07.2021", :routing=>nil, :_type=>"_doc", :pipeline=>"winlogbeat"}, #<LogStash::Event:0x1ab34a40>], :response=>{"index"=>{"_index"=>"winlogbeat-27.07.2021", "_type"=>"_doc", "_id"=>nil, "status"=>400, "error"=>{"type"=>"validation_exception", "reason"=>"Validation Failed: 1: this action would add [4] total shards, but this cluster currently has [998]/[1000] maximum shards open;"}}}}`


^ Not sure if this is helpful or not -

**Comment by a-d-a-m-b** [comment] 2021-08-02 11:11
Hi @dirka1 

This issue has popped up before. There are some commands that can help you get going again and some detail on the cause of the issue here: https://github.com/ukncsc/lme/issues/60#issuecomment-607302829

**Comment by a-d-a-m-b** [comment] 2021-09-10 17:20
Hi @dirka1 - is this now resolved?

**Comment by dirka1** [comment] 2021-09-10 20:04
I apologize for the delay in response, this did resolve my issue. Thank you!

**Comment by duncan-ncc** [comment] 2021-12-16 09:02
Closed as resolved.

**Closed as completed by duncan-ncc** 2021-12-16 09:02 UTC
Labels: bug
