### ISSUE TITLE
[BUG] Issue with logstash_writer Auth

### ISSUE THREAD

**Issue by splurggy** [ukncsc/lme#91] opened 2021-02-12 14:46 UTC
**Describe the issue**
New install of LME - the issue is in the elastic logs getting the error message :

docker service logs lme_elasticsearch

"Authentication to realm default_native failed - Password authentication failed for logstash_writer"

Checked all the config files for log stash under /opt/lme/'Chapter 3 Files'  logstash_editied.conf and the password i have when installed is matching.

no data into Kibana

Anybody else seen this ?

**Comment by a-d-a-m-b** [comment] 2021-02-12 18:18
Hi Splurggy - is your password in quotation marks within the logstash.conf file? This is occasionally the root cause of this issue (and will be fixed as part of the incoming bundled patches).

**Comment by splurggy** [comment] 2021-02-15 12:40
Hi - For some unknown reason i have left it over the weekend and its started working - Bizarre - thanks for replying

**Closed as completed** 2021-02-15 12:40 UTC
Labels: bug
