### ISSUE TITLE
Support Custom Logstash Files

### ISSUE THREAD

**Issue by Sommie99** [ukncsc/lme#102] opened 2021-05-17 15:22 UTC
I have been having issues with LME for a while now, but have only got around to properly testing.

It looks as though the data from the collector is not getting into the database

- I have updated LME to the latest version
- I have updated winlogbeat
- PDNS data is still pulling into the system

Servers send data to the collector ok, i have checked the winlogbeat log file which shows no errors and that it is publishing to the database server correctly.

I have checked the elasticsearch and logstash log files which show no errors - i had expected shard issues which i have had in the past when this happened

Any idea of other log files that may show an error that i can then resolve to fix this issue?

There doesnt seem to be any winlogbeat indexes

Many thanks

**Comment by duncan-ncc** [comment] 2021-05-17 16:00
Hi Sommie, 

Can you please post your logstash config please (with sensitive bits removed)
It sounds like the data isn't going through logstash properly.

**Comment by Sommie99** [comment] 2021-05-18 10:11
Hi,

I have 3 logstash files; logstash.conf, logstash_edited.conf and logstash_custom.conf

I know the NCSC PDNS data uses logstash_custom.conf file, yet this doesn’t contain the information for the winlogbeat.

Which file is used and which do you require the config for?

With you pointing me to the logstash.conf file I did notice I had forgotten to add the logstash_writer password, which I have now done.  But it hasn’t made any difference.  I do now however get errors with PDNS in the logstash log file

Thanks for your help
Alastair

**Comment by a-d-a-m-b** [comment] 2021-05-18 10:53
Adding an enhancement label as this is a good justification for allowing additional custom logstash files. We need to make sure that this will not break any installations and that it will not cause any conflicts with the provided LME configs so not sure what timescales we can expect a more permanent fix.  

We are discussing what can be done sooner though and we'll share via _temporary_ instructions.

**Comment by a-d-a-m-b** [comment] 2021-05-18 10:54
to help progress, can you share your logstash files? (with the sensitive bits redacted)

**Comment by Sommie99** [comment] 2021-05-18 12:43
Please see the zip file with my logstash files

Many thanks
Alastair


[logstash.edited.zip](https://github.com/ukncsc/lme/files/6501303/logstash.edited.zip)

**Comment by a-d-a-m-b** [comment] 2021-05-19 09:35
When multiple config files are provided, Logstash will flatten the contents into a single configuration in which to operate from. At the moment, your two config files have two output filters that are conflicting. This conflict can be resolved by adding in a tag field as part of the s3 input, wrapping the filter with and if statement and then wrapping the output in an if statement also. This approach can be seen in the project's logstash config.

As a short term and unsupported fix, you could add the tags and if statements as part of the logstash_custom.conf script. **This file is reserved for future use, and is not recommended to be used** so you should backup the file should you do any upgrades in the future. 

We will provide instructions as part of the next upgrade should any custom configs need to be preserved (as per other releases) in a more supported approach in a later release

An example (untested) logstash configuration that has the tags and if statements included has been provided below: 

```
# Sample Logstash configuration for ingesting PDNS data
# AWS S3 -> Logstash -> Elasticsearch pipeline.
# References:
#   https://www.elastic.co/guide/en/logstash/current/plugins-inputs-s3.html
#   https://www.elastic.co/blog/logstash-lines-inproved-resilience-in-S3-input
#   https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html
#   https://www.protectivedns.service.ncsc.gov.uk/pdns
#   https://www.ncsc.gov.uk/information/pdns

input {
  s3 {
    access_key_id => ""
    secret_access_key => ""
    bucket => ""
    role_arn => ""
    prefix => ""
    region => "eu-west-2"
    interval => 900
    tags => "pdns"
  }
}

filter {

  if "pdns" in [tags] {

    json {
      source => "message"
      target => "block"
    }

    split {
      field => "[block][payload][objects]"

      add_field => {
        "stix_event_type" => "%{[block][payload][objects][type]}" 
        "pdns_event_id" => "%{[block][payload][objects][id]}"
        "pdns_event_timestamp" => "%{[block][payload][objects][created]}"
        "pdns_event_count" => "%{[block][payload][objects][number_observed]}"
        "pdns_event_type" => "%{[block][payload][objects][objects][0][type]}"
        "pdns_query_qname" => "%{[block][payload][objects][objects][0][qname]}"
        "pdns_query_qtype" => "%{[block][payload][objects][objects][0][qtype]}"
        "pdns_query_qclass" => "%{[block][payload][objects][objects][0][qclass]}"
        "pdns_query_srcip-protocol" => "%{[block][payload][objects][objects][0][src_ip_network_type]}"
        "pdns_query_srcip" => "%{[block][payload][objects][objects][0][src_ip]}"
        "pdns_query_srcport" => "%{[block][payload][objects][objects][0][src_port]}"
        "pdns_threat_trigger" => "%{[block][payload][objects][objects][0][rpz_range]}"
        "pdns_threat_match" => "%{[block][payload][objects][objects][0][rpz_range_matched]}"
        "pdns_threat_layer" => "%{[block][payload][objects][objects][0][rpz_zone]}"
        "pdns_threat_source" => "%{[block][payload][objects][objects][1][type]}"
        "pdns_threat_feedname" => "%{[block][payload][objects][objects][1][name]}"
      }

    }

    if [block][payload][objects][objects][1][meta_data][0] {
      mutate {
        add_field => {
          "pdns_threat_%{[block][payload][objects][objects][1][meta_data][0][key]}" => "%{[block][payload][objects][objects][1][meta_data][0][value]}"
        }
      }
    }

    if [block][payload][objects][objects][1][meta_data][1] {
      mutate {
        add_field => {
          "pdns_threat_%{[block][payload][objects][objects][1][meta_data][1][key]}" => "%{[block][payload][objects][objects][1][meta_data][1][value]}"
        }
      }
    }

    if [block][payload][objects][objects][1][meta_data][2] {
      mutate {
        add_field => {
          "pdns_threat_%{[block][payload][objects][objects][1][meta_data][2][key]}" => "%{[block][payload][objects][objects][1][meta_data][2][value]}"
        }
      }
    }

    if [block][payload][objects][objects][1][meta_data][3] {
      mutate {
        add_field => {
          "pdns_threat_%{[block][payload][objects][objects][1][meta_data][3][key]}" => "%{[block][payload][objects][objects][1][meta_data][3][value]}"
        }
      }
    }

    if [block][payload][objects][objects][1][meta_data][4] {
      mutate {
        add_field => {
          "pdns_threat_%{[block][payload][objects][objects][1][meta_data][4][key]}" => "%{[block][payload][objects][objects][1][meta_data][4][value]}"
        }
      }
    }

    if [stix_event_type] != "observed-data" {
      drop {}
    } else {
      mutate {
        remove_field => ["stix_event_type"]
      }
    }

    geoip {
      source => "pdns_query_srcip"
    }
  
    mutate {
      remove_field => ["block", "message"]
    }
  }
}

output {
  if "pdns" in [tags] {
    elasticsearch {
      hosts => ["https://elasticsearch:9200"]
      index => "logstash-pdns-blocks-%{+YYYY.MM.dd}"
      user => logstash_writer
      password => ""
      ssl => true
      cacert => '/run/secrets/ca.crt'
    }
  }
}
```

**Comment by Sommie99** [comment] 2021-05-19 11:58
I tried to use the tags as suggested, but now seem to get the following in my logstash logs

`"2021-05-19T11:56:34.170304180Z lme_logstash.1.jl7i86d5erc5@lme-database2    | [2021-05-19T11:56:34,166][FATAL [org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit"
`
This is happening whether i am now using the tags or not.  How do i remove the logstash.custom.conf from being used to remove this from the equation.  I tried renaming the file, but that didnt work.  Unless i am looking  at the wrong files?

/opt/lme/Chapter 3 Files/
```

2021-05-19T11:56:22.835211510Z lme_logstash.1.jl7i86d5erc5@lme-database2    | [2021-05-19T11:56:22,834][INFO ][logstash.outputs.elasticsearch][main] ES Output version determined {:es_version=>7}
2021-05-19T11:56:22.835543733Z lme_logstash.1.jl7i86d5erc5@lme-database2    | [2021-05-19T11:56:22,835][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
2021-05-19T11:56:22.884193439Z lme_logstash.1.jl7i86d5erc5@lme-database2    | [2021-05-19T11:56:22,883][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["https://elasticsearch:9200"]}
2021-05-19T11:56:22.919373181Z lme_logstash.1.jl7i86d5erc5@lme-database2    | [2021-05-19T11:56:22,919][INFO ][logstash.filters.geoip   ][main] Using geoip database {:path=>"/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-geoip-6.0.5-java/vendor/GeoLite2-City.mmdb"}
2021-05-19T11:56:22.929468860Z lme_logstash.1.jl7i86d5erc5@lme-database2    | [2021-05-19T11:56:22,928][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
2021-05-19T11:56:23.079216079Z lme_logstash.1.jl7i86d5erc5@lme-database2    | [2021-05-19T11:56:23,078][INFO ][logstash.outputs.elasticsearch][main] Attempting to install template {:manage_template=>{"index_patterns"=>"logstash-*", "version"=>60001, "settings"=>{"index.refresh_interval"=>"5s", "number_of_shards"=>1}, "mappings"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}
2021-05-19T11:56:23.308064917Z lme_logstash.1.jl7i86d5erc5@lme-database2    | [2021-05-19T11:56:23,307][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>500, "pipeline.sources"=>["/usr/share/logstash/pipeline/logstash.conf", "/usr/share/logstash/pipeline/logstash_custom.conf"], :thread=>"#<Thread:0x3826cb51 run>"}
2021-05-19T11:56:25.336243195Z lme_logstash.1.jl7i86d5erc5@lme-database2    | [2021-05-19T11:56:25,335][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>2.03}
2021-05-19T11:56:25.365872286Z lme_logstash.1.jl7i86d5erc5@lme-database2    | [2021-05-19T11:56:25,365][INFO ][logstash.inputs.beats    ][main] Starting input listener {:address=>"0.0.0.0:5044"}
2021-05-19T11:56:26.193125768Z lme_logstash.1.jl7i86d5erc5@lme-database2    | [2021-05-19T11:56:26,192][INFO ][logstash.inputs.s3       ][main] Registering {:bucket=>"p-nom-59a54192-0b63-404e-bae3-b531c216e02c", :region=>"eu-west-2"}
2021-05-19T11:56:28.889168343Z lme_logstash.1.jl7i86d5erc5@lme-database2    | [2021-05-19T11:56:28,888][ERROR][logstash.javapipeline    ][main] Pipeline error {:pipeline_id=>"main", :exception=>#<Aws::STS::Errors::AccessDenied: User: arn:aws:iam::############:user/p-nom-blk-41 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::############:role/p-nom-blk-41/>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/plugins/response_target.rb:21:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/request.rb:70:in `send_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/base.rb:207:in `block in define_operation_methods'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/assume_role_credentials.rb:49:in `refresh'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/refreshing_credentials.rb:20:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/assume_role_credentials.rb:40:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-mixin-aws-4.4.1/lib/logstash/plugin_mixins/aws_config/v2.rb:67:in `assume_role'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-mixin-aws-4.4.1/lib/logstash/plugin_mixins/aws_config/v2.rb:17:in `aws_options_hash'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-3.5.0/lib/logstash/inputs/s3.rb:416:in `get_s3object'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-3.5.0/lib/logstash/inputs/s3.rb:96:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:228:in `block in register_plugins'", "org/jruby/RubyArray.java:1809:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:227:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:386:in `start_inputs'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:311:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:185:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:137:in `block in start'"], "pipeline.sources"=>["/usr/share/logstash/pipeline/logstash.conf", "/usr/share/logstash/pipeline/logstash_custom.conf"], :thread=>"#<Thread:0x3826cb51 run>"}
2021-05-19T11:56:28.890209708Z lme_logstash.1.jl7i86d5erc5@lme-database2    | [2021-05-19T11:56:28,890][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
2021-05-19T11:56:28.902032106Z lme_logstash.1.jl7i86d5erc5@lme-database2    | [2021-05-19T11:56:28,901][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}
2021-05-19T11:56:29.120262682Z lme_logstash.1.jl7i86d5erc5@lme-database2    | [2021-05-19T11:56:29,119][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
2021-05-19T11:56:34.157428253Z lme_logstash.1.jl7i86d5erc5@lme-database2    | [2021-05-19T11:56:34,157][INFO ][logstash.runner          ] Logstash shut down.
2021-05-19T11:56:34.170304180Z lme_logstash.1.jl7i86d5erc5@lme-database2    | [2021-05-19T11:56:34,166][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
2021-05-19T11:56:34.170326764Z lme_logstash.1.jl7i86d5erc5@lme-database2    | org.jruby.exceptions.SystemExit: (SystemExit) exit
2021-05-19T11:56:34.170333616Z lme_logstash.1.jl7i86d5erc5@lme-database2    |   at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:747) ~[jruby-complete-9.2.13.0.jar:?]
2021-05-19T11:56:34.170339749Z lme_logstash.1.jl7i86d5erc5@lme-database2    |   at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:710) ~[jruby-complete-9.2.13.0.jar:?]
2021-05-19T11:56:34.170345634Z lme_logstash.1.jl7i86d5erc5@lme-database2    |   at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:89) ~[?:?]
2021-05-19T11:56:40.779355314Z lme_logstash.1.6fr56fip75oe@lme-database2    | 2021/05/19 11:56:40 Setting 'xpack.monitoring.enabled' from environment.
2021-05-19T11:56:40.787782326Z lme_logstash.1.6fr56fip75oe@lme-database2    | Using bundled JDK: /usr/share/logstash/jdk
2021-05-19T11:56:40.798763856Z lme_logstash.1.6fr56fip75oe@lme-database2    | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

```

**Comment by a-d-a-m-b** [comment] 2021-05-19 12:48
Looks like an AWS access error is the cause of the issue.

```<Aws::STS::Errors::AccessDenied: User: arn:aws:iam::############:user/p-nom-blk-41 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::############:role/p-nom-blk-41/>```

If you want to remove the file to get LME working again, then backup the file that you have and create an empty logstash_custom.conf file. Or you could comment out the lines

**Comment by adam-ncc** [comment] 2022-03-08 17:54
Hey @Sommie99, were you able to get this working in the end or is this still causing issues?

**Comment by duncan-ncc** [comment] 2023-04-03 08:05
Closed due to project archive

**Closed as not planned by duncan-ncc** 2023-04-03 08:05 UTC
Labels: enhancement
